import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import Team from "../public/robot.PNG";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Quanta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className={styles.parent}>
          <div className="mt-44 ml-20 leading-9 max-sm:ml-3 text-center">
            <h1 className=" text-6xl font-bold uppercase text-black-800 max-sm:ml-0">
              Quanta robotics
            </h1>
            <p className="text-right m-2 text-blue-500  font-bold max-sm:text-center ">
              Born for innovation
            </p>
          </div>

          <div>
            <h1 className="mt-40 text-6xl font-bold uppercase text-blue-700 max-sm:mt-1 max-sm:text-center ">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="currentColor"
                className="w-20 h-20"
              >
                <path
                  fillRule="evenodd"
                  d="M9.315 7.584C12.195 3.883 16.695 1.5 21.75 1.5a.75.75 0 01.75.75c0 5.056-2.383 9.555-6.084 12.436A6.75 6.75 0 019.75 22.5a.75.75 0 01-.75-.75v-4.131A15.838 15.838 0 016.382 15H2.25a.75.75 0 01-.75-.75 6.75 6.75 0 017.815-6.666zM15 6.75a2.25 2.25 0 100 4.5 2.25 2.25 0 000-4.5z"
                  clipRule="evenodd"
                />
                <path d="M5.26 17.242a.75.75 0 10-.897-1.203 5.243 5.243 0 00-2.05 5.022.75.75 0 00.625.627 5.243 5.243 0 005.022-2.051.75.75 0 10-1.202-.897 3.744 3.744 0 01-3.008 1.51c0-1.23.592-2.323 1.51-3.008z" />
              </svg>
              invincible innovation
            </h1>
          </div>
        </div>
        <div className="section-2 grid grid-cols-2 max-sm:grid-cols-1">
          <div>
            {" "}
            <Image className="" src={Team} alt="Team" />
          </div>

          <div className="mt-20 grid grid-cols-2 max-sm:grid-cols-1 ">
           
            <div className="shadow-xl max-sm:shadow-md w-80 p-6 rounded shadow-indigo-500/50 h-44 max-sm:grid-cols-1 max-sm:w-96 max-sm:text-left"> 
            <h1 className="font-bold text-2xl uppercase text-blue-600">Quanta robotics </h1>
            <p className="font-semibold text-sm">text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,  </p>
            </div>

            <div className="shadow-xl  max-sm:shadow-md w-80 p-6 rounded shadow-indigo-500/50  h-44 mt-44 max-sm:mt-10 max-sm:grid-cols-1 max-sm:w-96 max-sm:text-right"> 
            <h1 className="font-bold text-2xl uppercase  text-blue-600">Quanta robotics </h1>
            <p className="font-semibold text-sm">text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,  </p>
            </div>

            <div className="shadow-xl w-80 p-6 rounded shadow-indigo-500/50  h-44 mt-4 max-sm:mt-10 max-sm:grid-cols-1 max-sm:w-96 max-sm:text-left"> 
            <h1 className="font-bold text-2xl uppercase  text-blue-600">Quanta robotics </h1>
            <p className="font-semibold text-sm">text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,  </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
